swagger: '2.0'
info:
  description: Coupang Order Status
  version: '1.0'
  title: Coupang Order Status
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: order-api-controller
    description: Order Api Controller
paths:
  '/v2/providers/avocado/apis/api/v1/vendors/fanatics/orders/{orderId}/packages/{trackingId}':
    put:
      tags:
        - order-api-controller
      summary: orderTracking
      operationId: orderTrackingUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: orderId
          required: true
          type: string
        - name: trackingId
          in: path
          description: trackingId
          required: true
          type: string
        - in: body
          name: orderPackage
          description: orderPackage
          required: true
          schema:
            $ref: '#/definitions/OrderPackage'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/v2/providers/avocado/apis/api/v1/vendors/fanatics/orders/{orderId}/status/':
    put:
      tags:
        - order-api-controller
      summary: orderStatus
      operationId: orderStatusUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          description: orderId
          required: true
          type: string
        - in: body
          name: orderStatus
          description: orderStatus
          required: true
          schema:
            $ref: '#/definitions/OrderStatus'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  OrderItem:
    type: object
    properties:
      itemId:
        type: string
      quantity:
        type: integer
        format: int32
    title: OrderItem
  OrderPackage:
    type: object
    properties:
      orderId:
        type: string
      packageLines:
        type: array
        items:
          $ref: '#/definitions/OrderItem'
      trackingId:
        type: string
      trackingUrl:
        type: string
    title: OrderPackage
  OrderStatus:
    type: object
    properties:
      availableItems:
        type: array
        items:
          type: string
      unavailableItems:
        type: array
        items:
          type: string
    title: OrderStatus
  Response:
    type: object
    properties:
      success:
        type: boolean
    title: Response